version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: serverless
    versions:
    - 2.36.0
    - 2.37.0
    - 2.37.2
  - dependency-name: webpack
    versions:
    - 5.34.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.10
    - 24.1.9
    - 24.2.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.0
  - dependency-name: "@babel/plugin-proposal-optional-chaining"
    versions:
    - 7.12.13
