# Hello World for AWS Lambda
service: battlebit-auth-service # Service Name

# Add the serverless-webpack plugin
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    service_name: ${self:service}

functions:
  signup:
    handler: src/api/signup/index.handler
    events:
      - http:
          method: post
          path: /signup

package:
  individually: true

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: yarn
